'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState, type KeyboardEvent } from 'react';

type Platform = 'codeforces' | 'luogu' | 'qoj';
type Range = { kind: 'rolling'; days: 7 | 30 } | { kind: 'fixed'; from: string; to: string };
type Settings = { platforms: Platform[]; autoSyncEnabled: boolean; syncIntervalMinutes: number; scoreRange: Range; version: number; items: Summary[] };
type Summary = { platform: Platform; bindingCount: number; submissionCount: number; problemCount: number; lastSuccessAt: string | null; nextSyncAt: string | null; blockedCount: number; skipped: string | null; message: string | null };
type Rate = { minIntervalMs: number; maxIntervalMs: number; version: number };
type PlatformInfo = { platform: Platform; name: string; rateLimit: Rate; connection: { state: string; collector: string | null } };
type Job = { id: string; platform: Platform; username: string; handle: string | null; source: string; kind: string; mode: string; status: string; pages: number; recordsWithOverlap: number; batch: number; range: { from: string; to: string } | null; createdAt: string; startedAt: string | null; finishedAt: string | null; error: { code?: string; message?: string } | null };
type Jobs = { items: Job[]; nextCursor: string | null };
type Leaderboard = { range: { from: string; to: string }; provisional: boolean; total: number; items: { id: string; rank: number; displayName: string; points: number; solveCount: number; lastAcAt: string | null }[] };
type Initial = { settings: Settings; platforms: PlatformInfo[]; control: { enabled: boolean; version: number }; jobs: Jobs; leaderboard: Leaderboard };
type DispatchResult = { items: { runId?: string; merged?: boolean; skipped?: string; message?: string; error?: { message: string } }[] };
const labels: Record<Platform, string> = { codeforces: 'Codeforces', luogu: '洛谷', qoj: 'QOJ' };
const statuses: Record<string, string> = { queued: '排队中', running: '采集中', completed: '已完成', paused: '已暂停', failed: '失败', cancelled: '已取消' };
const sources: Record<string, string> = { manual: '手动更新', scheduled: '定时同步', binding: '绑定验证', settings: '设置更新', rebuild: '清空重爬' };
const buttonBase = 'rounded-lg border px-4 py-2 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50';
const button = `${buttonBase} border-slate-300 bg-white hover:bg-slate-50`;
const primary = `${buttonBase} border-blue-700 bg-blue-700 text-white hover:bg-blue-800`;
const danger = `${buttonBase} border-red-700 bg-red-700 text-white hover:bg-red-800`;
const field = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const panel = 'rounded-2xl border border-slate-200 bg-white p-5 sm:p-6';
function time(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '—'; }
function outcome(data: DispatchResult) {
  const count = data.items.filter(item => item.runId && !item.merged).length;
  const merged = data.items.filter(item => item.merged).length;
  const skips = [...new Set(data.items.filter(item => item.skipped || item.error).map(item => item.message ?? item.error?.message ?? item.skipped))];
  return `新建 ${count} 个任务，合并 ${merged} 个已有任务。${skips.join('；')}`;
}
export function CollectionManager({ csrfToken, initial }: { csrfToken: string; initial: Initial }) {
  const [settings, setSettings] = useState(initial.settings), [draft, setDraft] = useState(initial.settings);
  const [platforms, setPlatforms] = useState(initial.platforms), [rates, setRates] = useState(Object.fromEntries(initial.platforms.map(p => [p.platform, p.rateLimit])) as Record<Platform, Rate>);
  const [control, setControl] = useState(initial.control), [jobs, setJobs] = useState(initial.jobs), [leaderboard, setLeaderboard] = useState(initial.leaderboard);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [pollError, setPollError] = useState('');
  const [cursor, setCursor] = useState<string | null>(null), [previousCursors, setPreviousCursors] = useState<(string | null)[]>([]);
  const [resetPlatforms, setResetPlatforms] = useState<Platform[]>([]), [reset, setReset] = useState<{ requestId: string; version: number } | null>(null);
  const [resetAttempted, setResetAttempted] = useState(false);
  const call = useCallback(async <T,>(url: string, method = 'GET', body?: unknown): Promise<T> => {
    const response = await fetch(url, { method, credentials: 'same-origin', cache: 'no-store', signal: AbortSignal.timeout(70000), headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrfToken }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    const data = await response.json();
    if (!response.ok) throw new Error(data.message ?? '操作失败'); return data as T;
  }, [csrfToken]);
  const refresh = useCallback(async () => {
    const [s, p, c, j, l] = await Promise.all([call<Settings>('/api/admin/collection-settings'), call<{ items: PlatformInfo[] }>('/api/admin/platforms'), call<Initial['control']>('/api/admin/collection-control'), call<Jobs>(`/api/admin/sync-jobs${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`), call<Leaderboard>('/api/leaderboard')]);
    setSettings(s); setPlatforms(p.items); setControl(c); setJobs(j); setLeaderboard(l); setPollError('');
    return { settings: s, platforms: p.items };
  }, [call, cursor]);
  useEffect(() => {
    let stopped = false, pending = false;
    const poll = async () => { if (stopped || pending || document.hidden) return; pending = true; try { await refresh(); } catch (error) { if (!stopped) setPollError(error instanceof Error ? error.message : '刷新失败'); } finally { pending = false; } };
    void poll(); const timer = setInterval(() => void poll(), 5000);
    return () => { stopped = true; clearInterval(timer); };
  }, [refresh]);
  async function action(fn: () => Promise<void>) {
    setBusy(true); setMessage('');
    try { await fn(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败，请刷新后重试'); } finally { setBusy(false); }
  }
  const setRange = (range: Range) => setDraft({ ...draft, scoreRange: range });
  const selectedSummary = settings.items.filter(item => resetPlatforms.includes(item.platform));
  function dialogKeys(event: KeyboardEvent<HTMLElement>) {
    if (event.key === 'Escape' && !busy) { setReset(null); return; }
    if (event.key !== 'Tab') return;
    const controls = event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled)');
    const first = controls[0], last = controls[controls.length - 1];
    if (event.shiftKey && document.activeElement === first && last) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && document.activeElement === last && first) { event.preventDefault(); first.focus(); }
  }
  return <div className="space-y-6">
    <section className={panel}>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">采集总开关</h2><p className="mt-2 text-sm text-slate-600">当前{control.enabled ? '已启用' : '已暂停'}。CF 无需平台登录；其他平台可在需要时加入。</p></div><button className={button} disabled={busy} onClick={() => void action(async () => { setControl(await call('/api/admin/collection-control', 'PUT', { enabled: !control.enabled, version: control.version })); setMessage(control.enabled ? '采集已暂停，已入库数据保留。' : '采集已恢复。'); })}>{control.enabled ? '暂停采集' : '启用采集'}</button></div>
      <div className="mt-5 flex flex-wrap gap-3"><button className={primary} disabled={busy || !control.enabled || !settings.platforms.length} onClick={() => void action(async () => { const result = await call<DispatchResult>('/api/admin/sync', 'POST', {}); setMessage(outcome(result)); })}>立即更新积分</button><button className={button} disabled={busy} onClick={() => void action(async () => { const data = await refresh(); setDraft(data.settings); setRates(Object.fromEntries(data.platforms.map(p => [p.platform, p.rateLimit])) as Record<Platform, Rate>); setMessage('已重新读取最新设置。'); })}>重新读取设置</button></div>
      <p role="status" aria-live="polite" className="mt-4 min-h-5 text-sm text-blue-800">{busy ? '正在处理，请稍候…' : message}</p>{pollError && <p role="alert" className="mt-2 text-sm text-red-700">自动刷新失败：{pollError}</p>}
    </section>
    <section className={panel}>
      <h2 className="text-lg font-semibold">平台、日期与自动同步</h2><p className="mt-2 text-sm text-slate-600">平台开关同时控制爬取和计分。保存平台或区间后立即更新，暂停时等待恢复。</p>
      <fieldset className="mt-5 flex flex-wrap gap-6" disabled={busy}><legend className="sr-only">参与平台</legend>{(['codeforces', 'luogu', 'qoj'] as const).map(platform => <label key={platform} className="flex items-center gap-2"><input type="checkbox" checked={draft.platforms.includes(platform)} onChange={e => setDraft({ ...draft, platforms: e.target.checked ? [...draft.platforms, platform] : draft.platforms.filter(p => p !== platform) })} />{labels[platform]}</label>)}</fieldset>
      <div className="mt-5 grid gap-5 md:grid-cols-2"><div><label className="block text-sm font-medium" htmlFor="score-range">计分与爬取区间（北京时间）</label><select id="score-range" className={`${field} mt-2 w-full`} disabled={busy} value={draft.scoreRange.kind === 'fixed' ? 'fixed' : String(draft.scoreRange.days)} onChange={e => setRange(e.target.value === 'fixed' ? { kind: 'fixed', from: leaderboard.range.from, to: leaderboard.range.to } : { kind: 'rolling', days: Number(e.target.value) as 7 | 30 })}><option value="7">滚动近 7 天（包含今天）</option><option value="30">滚动近 30 天（包含今天）</option><option value="fixed">自定义起止日期</option></select>{draft.scoreRange.kind === 'fixed' && <div className="mt-3 flex flex-wrap items-center gap-3"><label className="text-sm">开始<input aria-label="开始日期" type="date" className={`${field} ml-2`} value={draft.scoreRange.from} disabled={busy} onChange={e => { if (draft.scoreRange.kind === 'fixed') setRange({ ...draft.scoreRange, from: e.target.value }); }} /></label><label className="text-sm">结束<input aria-label="结束日期" type="date" className={`${field} ml-2`} value={draft.scoreRange.to} disabled={busy} onChange={e => { if (draft.scoreRange.kind === 'fixed') setRange({ ...draft.scoreRange, to: e.target.value }); }} /></label><p className="text-xs text-slate-500">包含首尾日期，最多 366 天。</p></div>}</div><div><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" disabled={busy} checked={draft.autoSyncEnabled} onChange={e => setDraft({ ...draft, autoSyncEnabled: e.target.checked })} />开启自动增量同步</label><label className="mt-3 block text-sm">统一同步周期<input className={`${field} mx-2 w-28`} type="number" min={1} max={10080} disabled={busy} value={draft.syncIntervalMinutes} onChange={e => setDraft({ ...draft, syncIntervalMinutes: Number(e.target.value) })} />分钟</label><p className="mt-2 text-xs text-slate-500">1 分钟至 7 天；360 分钟为 6 小时。平台的 HTTP 请求间隔在下面单独设置。</p></div></div>
      {settings.version !== draft.version && <p role="alert" className="mt-4 text-sm text-amber-800">设置已被其他管理员修改，请重新读取后保存。</p>}
      <button className={`${primary} mt-5`} disabled={busy || settings.version !== draft.version} onClick={() => void action(async () => { const result = await call<{ settings: Settings } & DispatchResult>('/api/admin/collection-settings', 'PUT', { platforms: draft.platforms, autoSyncEnabled: draft.autoSyncEnabled, syncIntervalMinutes: draft.syncIntervalMinutes, scoreRange: draft.scoreRange, version: draft.version }); setDraft({ ...draft, ...result.settings }); setMessage(`设置已保存。${outcome(result)}`); })}>保存设置</button>
    </section>
    <section className="grid gap-4 lg:grid-cols-3" aria-label="平台采集状态">{platforms.map(platform => {
      const summary = settings.items.find(item => item.platform === platform.platform), rate = rates[platform.platform];
      return <article key={platform.platform} className={panel}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{platform.name}</h2><span className={`rounded-full px-3 py-1 text-xs ${settings.platforms.includes(platform.platform) ? 'bg-blue-50 text-blue-800' : 'bg-slate-100 text-slate-600'}`}>{settings.platforms.includes(platform.platform) ? '参与采集与计分' : '未启用'}</span></div><p className="mt-3 text-sm">{platform.connection.state === 'not_required' ? '公开 API，无需登录' : `登录：${platform.connection.state === 'ready' ? '已就绪' : '待登录/核验'} · ${platform.connection.collector ?? '未核验身份'}`}</p><p className="mt-2 text-sm text-amber-800">{summary?.message ?? (summary?.blockedCount ? `${summary.blockedCount} 个目标已暂停，请检查任务错误。` : '可正常采集')}</p><dl className="mt-4 space-y-2 text-sm text-slate-600"><div>生效绑定：{summary?.bindingCount ?? 0}</div><div>本地题目 / 提交：{summary?.problemCount ?? 0} / {summary?.submissionCount ?? 0}</div><div>最近成功：{time(summary?.lastSuccessAt ?? null)}</div><div>下次同步：{time(summary?.nextSyncAt ?? null)}</div></dl>{platform.platform !== 'codeforces' && <Link className="mt-3 inline-block text-sm text-blue-700" href="/admin/connections">登录或核验平台 →</Link>}<fieldset className="mt-5 border-t pt-4" disabled={busy}><legend className="pt-3 text-sm font-medium">单次请求随机间隔（毫秒）</legend><div className="mt-2 flex items-center gap-2"><input aria-label={`${platform.name}最小请求间隔`} className={`${field} w-full min-w-0`} type="number" min={platform.platform === 'codeforces' ? 2000 : 1000} max={60000} value={rate.minIntervalMs} onChange={e => setRates({ ...rates, [platform.platform]: { ...rate, minIntervalMs: Number(e.target.value) } })} /><span>至</span><input aria-label={`${platform.name}最大请求间隔`} className={`${field} w-full min-w-0`} type="number" min={rate.minIntervalMs} max={60000} value={rate.maxIntervalMs} onChange={e => setRates({ ...rates, [platform.platform]: { ...rate, maxIntervalMs: Number(e.target.value) } })} /></div><button className={`${button} mt-3`} onClick={() => void action(async () => { const updated = await call<Rate>(`/api/admin/platforms/${platform.platform}/rate-limit`, 'PATCH', { minIntervalMs: rate.minIntervalMs, maxIntervalMs: rate.maxIntervalMs, version: rate.version }); setRates({ ...rates, [platform.platform]: updated }); setMessage(`${platform.name}请求间隔已保存。`); })}>保存请求间隔</button></fieldset></article>;
    })}</section>
    <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">同步任务</h2><p className="mt-2 text-sm text-slate-500">每 5 秒刷新。提交数含翻页重叠，不等于首次 AC 题数。</p></div><div className="flex gap-2"><button className={button} disabled={busy || !previousCursors.length} onClick={() => { setCursor(previousCursors.at(-1) ?? null); setPreviousCursors(previousCursors.slice(0, -1)); }}>上一页</button><button className={button} disabled={busy || !jobs.nextCursor} onClick={() => { setPreviousCursors([...previousCursors, cursor]); setCursor(jobs.nextCursor); }}>下一页</button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b text-slate-500"><tr>{['目标 / 平台', '来源 / 区间', '状态 / 进度', '入队 / 开始 / 完成', '错误与操作'].map(text => <th className="px-3 py-3 font-medium" key={text}>{text}</th>)}</tr></thead><tbody>{jobs.items.map(job => <tr key={job.id} className="border-b align-top last:border-0"><td className="px-3 py-3"><div>{job.handle ?? job.username}</div><div className="mt-1 text-xs text-slate-500">{labels[job.platform]} · {job.kind === 'verify' ? '账号验证' : job.mode === 'backfill' ? '回填' : '增量'}</div></td><td className="px-3 py-3"><div>{sources[job.source] ?? job.source}</div><div className="mt-1 whitespace-nowrap text-xs text-slate-500">{job.range ? `${job.range.from} 至 ${job.range.to}` : '—'}</div></td><td className="px-3 py-3"><div>{statuses[job.status] ?? job.status}</div><div className="mt-1 whitespace-nowrap text-xs text-slate-500">{job.pages} 页 · {job.recordsWithOverlap} 条 · 第 {job.batch + 1} 批</div></td><td className="px-3 py-3 text-xs text-slate-500"><div>{time(job.createdAt)}</div><div>{time(job.startedAt)}</div><div>{time(job.finishedAt)}</div></td><td className="px-3 py-3"><p className="max-w-64 text-xs text-red-700">{job.error?.message ?? job.error?.code ?? '—'}</p>{['failed', 'paused'].includes(job.status) && <button className={`${button} mt-2`} disabled={busy || !control.enabled} onClick={() => void action(async () => { await call(`/api/admin/sync-jobs/${job.id}/retry`, 'POST', {}); setMessage('重试任务已入队。'); })}>重试</button>}</td></tr>)}</tbody></table>{!jobs.items.length && <p className="py-8 text-center text-sm text-slate-500">暂无同步任务。绑定平台账号后可开始更新。</p>}</div></section>
    <section className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">当前积分榜预览</h2><p className="mt-2 text-sm text-slate-600">{leaderboard.range.from} 至 {leaderboard.range.to} · 北京时间 · {leaderboard.total} 位成员</p></div><span className={`rounded-full px-3 py-1 text-xs ${leaderboard.provisional ? 'bg-amber-50 text-amber-800' : 'bg-emerald-50 text-emerald-800'}`}>{leaderboard.provisional ? '历史采集未完整，积分暂定' : '已采集数据计算完成'}</span></div><p className="mt-3 text-xs text-slate-500">首次 AC 按全部已采集有效记录确定，积分采用当前题目难度与 v1 规则。这里显示前 20 位。</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b text-slate-500"><tr>{['名次', '成员', '积分', '首次 AC 题数', '最近首次 AC'].map(text => <th key={text} className="px-3 py-3 font-medium">{text}</th>)}</tr></thead><tbody>{leaderboard.items.map(item => <tr key={item.id} className="border-b last:border-0"><td className="px-3 py-3">{item.rank}</td><td className="px-3 py-3 font-medium">{item.displayName}</td><td className="px-3 py-3 text-blue-800">{item.points}</td><td className="px-3 py-3">{item.solveCount}</td><td className="px-3 py-3 text-slate-500">{time(item.lastAcAt)}</td></tr>)}</tbody></table>{!leaderboard.items.length && <p className="py-6 text-center text-sm text-slate-500">暂无成员。</p>}</div></section>
    <section className={`${panel} border-red-200`}><h2 className="text-lg font-semibold text-red-800">清空所选平台并重爬</h2><p className="mt-2 text-sm text-slate-600">删除所选平台的题目、提交及采集游标，再按当前区间回填。用户、账号绑定、登录、设置和其他平台数据均保留。</p><button className={`${button} mt-4 border-red-300 text-red-800`} disabled={busy || !control.enabled || !settings.items.some(item => !item.skipped)} onClick={() => { setMessage(''); setResetPlatforms(settings.items.filter(item => !item.skipped).map(item => item.platform)); setReset({ requestId: crypto.randomUUID(), version: settings.version }); setResetAttempted(false); }}>选择重爬平台…</button></section>
    {reset && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/50 p-4"><section role="dialog" onKeyDown={dialogKeys} aria-modal="true" aria-labelledby="reset-title" className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><h2 id="reset-title" className="text-xl font-semibold text-red-800">确认清空后重爬</h2><p className="mt-3 text-sm text-slate-600">请选择已启用、已登录且存在生效绑定的平台。清空后积分会随回填逐步恢复。</p><fieldset disabled={busy || resetAttempted} className="mt-4 space-y-3">{settings.items.filter(item => settings.platforms.includes(item.platform)).map(item => <label key={item.platform} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={resetPlatforms.includes(item.platform)} disabled={Boolean(item.skipped)} onChange={e => setResetPlatforms(e.target.checked ? [...resetPlatforms, item.platform] : resetPlatforms.filter(p => p !== item.platform))} /><span>{labels[item.platform]}：{item.submissionCount} 条提交、{item.problemCount} 道题目{item.message ? ` · ${item.message}` : ''}</span></label>)}</fieldset><p className="mt-4 text-sm font-medium">合计清理 {selectedSummary.reduce((n, p) => n + p.submissionCount, 0)} 条提交、{selectedSummary.reduce((n, p) => n + p.problemCount, 0)} 道题目。</p><p className="mt-2 text-xs text-slate-500">重爬区间：{leaderboard.range.from} 至 {leaderboard.range.to}，北京时间。</p><div className="mt-6 flex flex-wrap justify-end gap-3"><button autoFocus className={button} disabled={busy} onClick={() => setReset(null)}>取消</button><button className={danger} disabled={busy || !resetPlatforms.length || settings.version !== reset.version} onClick={() => void action(async () => { setResetAttempted(true); const result = await call<DispatchResult>('/api/admin/collection-reset', 'POST', { platforms: resetPlatforms, version: reset.version, requestId: reset.requestId }); setReset(null); setMessage(`已清空并开始重爬。${outcome(result)}`); })}>确认清空并重爬</button></div>{!busy && message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</section></div>}
  </div>;
}
