'use client';
import type { Dispatch, SetStateAction } from 'react';
import type { Jobs, Initial } from '@acm/core/contracts';
import { syncScopes, syncStatuses as statuses, syncSources as sources } from '@acm/core/contracts';
import { platformNames as labels } from '@acm/connectors/metadata';
const buttonBase = 'rounded-lg border px-4 py-2 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50';
const button = `${buttonBase} border-slate-300 bg-white hover:bg-slate-50`;
const panel = 'rounded-2xl border border-slate-200 bg-white p-5 sm:p-6';
function time(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '—'; }

export function JobsPanel({ jobs, busy, control, previousCursors, cursor, setCursor, setPreviousCursors, retry }: { jobs: Jobs; busy: boolean; control: Initial['control']; previousCursors: (string | null)[]; cursor: string | null; setCursor: Dispatch<SetStateAction<string | null>>; setPreviousCursors: Dispatch<SetStateAction<(string | null)[]>>; retry: (id: string) => void }) {
  return <>
    <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">同步任务</h2><p className="mt-2 text-sm text-slate-500">每 5 秒刷新。提交数含翻页重叠，不等于首次 AC 题数。</p></div><div className="flex gap-2"><button className={button} disabled={busy || !previousCursors.length} onClick={() => { setCursor(previousCursors.at(-1) ?? null); setPreviousCursors(previousCursors.slice(0, -1)); }}>上一页</button><button className={button} disabled={busy || !jobs.nextCursor} onClick={() => { setPreviousCursors([...previousCursors, cursor]); setCursor(jobs.nextCursor); }}>下一页</button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b text-slate-500"><tr>{['目标 / 平台', '来源 / 区间', '状态 / 进度', '入队 / 开始 / 完成', '错误与操作'].map(text => <th className="px-3 py-3 font-medium" key={text}>{text}</th>)}</tr></thead><tbody>{jobs.items.map(job => <tr key={job.id} className="border-b align-top last:border-0"><td className="px-3 py-3"><div>{job.handle ?? job.username}</div><div className="mt-1 text-xs text-slate-500">{labels[job.platform]} · {job.kind === 'verify' ? '账号验证' : syncScopes[job.scope]}</div></td><td className="px-3 py-3"><div>{sources[job.source] ?? job.source}</div><div className="mt-1 whitespace-nowrap text-xs text-slate-500">{job.range ? `${job.range.from} 至 ${job.range.to}` : job.initialFrom ? `${time(job.initialFrom)} 起` : '从已完成检查点继续'}</div></td><td className="px-3 py-3"><div>{statuses[job.status] ?? job.status}</div><div className="mt-1 whitespace-nowrap text-xs text-slate-500">{job.pages} 页 · {job.recordsWithOverlap} 条 · 第 {job.batch + 1} 批</div></td><td className="px-3 py-3 text-xs text-slate-500"><div>{time(job.createdAt)}</div><div>{time(job.startedAt)}</div><div>{time(job.finishedAt)}</div></td><td className="px-3 py-3"><p className="max-w-64 text-xs text-red-700">{job.error?.message ?? job.error?.code ?? '—'}</p>{['failed', 'paused'].includes(job.status) && <button className={`${button} mt-2`} disabled={busy || !control.enabled} onClick={() => retry(job.id)}>重试</button>}</td></tr>)}</tbody></table>{!jobs.items.length && <p className="py-8 text-center text-sm text-slate-500">暂无同步任务。绑定平台账号后可开始更新。</p>}</div></section>

  </>;
}
