'use client';
import type { KeyboardEvent, Dispatch, SetStateAction } from 'react';
import type { Platform, Settings, Leaderboard, Initial } from '@acm/core/contracts';
import { platformNames as labels } from '@acm/connectors/metadata';
const buttonBase = 'rounded-lg border px-4 py-2 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50';
const button = `${buttonBase} border-slate-300 bg-white hover:bg-slate-50`;
const danger = `${buttonBase} border-red-700 bg-red-700 text-white hover:bg-red-800`;
const panel = 'rounded-2xl border border-slate-200 bg-white p-5 sm:p-6';

export function ResetPanel({ settings, control, busy, leaderboard, reset, resetAttempted, resetPlatforms, selectedSummary, message, setReset, setResetPlatforms, dialogKeys, open, confirm }: { settings: Settings; control: Initial['control']; busy: boolean; leaderboard: Leaderboard; reset: { requestId: string; version: number } | null; resetAttempted: boolean; resetPlatforms: Platform[]; selectedSummary: Settings['items']; message: string; setReset: Dispatch<SetStateAction<{ requestId: string; version: number } | null>>; setResetPlatforms: Dispatch<SetStateAction<Platform[]>>; dialogKeys: (event: KeyboardEvent<HTMLElement>) => void; open: () => void; confirm: () => void }) {
  return <>
    <section className={`${panel} border-red-200`}><h2 className="text-lg font-semibold text-red-800">清空所选平台并重爬</h2><p className="mt-2 text-sm text-slate-600">删除所选平台的题目、提交及采集游标，再按所选区间补采并恢复持续增量。用户、账号绑定、登录、设置和其他平台数据均保留。</p><button className={`${button} mt-4 border-red-300 text-red-800`} disabled={busy || !control.enabled || !settings.items.some(item => !item.skipped)} onClick={open}>选择重爬平台…</button></section>
    {reset && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/50 p-4"><section role="dialog" onKeyDown={dialogKeys} aria-modal="true" aria-labelledby="reset-title" className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><h2 id="reset-title" className="text-xl font-semibold text-red-800">确认清空后重爬</h2><p className="mt-3 text-sm text-slate-600">请选择已启用、已登录且存在生效绑定的平台。清空后积分会随回填逐步恢复。</p><fieldset disabled={busy || resetAttempted} className="mt-4 space-y-3">{settings.items.filter(item => settings.platforms.includes(item.platform)).map(item => <label key={item.platform} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={resetPlatforms.includes(item.platform)} disabled={Boolean(item.skipped)} onChange={e => setResetPlatforms(e.target.checked ? [...resetPlatforms, item.platform] : resetPlatforms.filter(p => p !== item.platform))} /><span>{labels[item.platform]}：{item.submissionCount} 条提交、{item.problemCount} 道题目{item.message ? ` · ${item.message}` : ''}</span></label>)}</fieldset><p className="mt-4 text-sm font-medium">合计清理 {selectedSummary.reduce((n, p) => n + p.submissionCount, 0)} 条提交、{selectedSummary.reduce((n, p) => n + p.problemCount, 0)} 道题目。</p><p className="mt-2 text-xs text-slate-500">重爬区间：{leaderboard.range.from} 至 {leaderboard.range.to}，北京时间。</p><div className="mt-6 flex flex-wrap justify-end gap-3"><button autoFocus className={button} disabled={busy} onClick={() => setReset(null)}>取消</button><button className={danger} disabled={busy || !resetPlatforms.length || settings.version !== reset.version} onClick={confirm}>确认清空并重爬</button></div>{!busy && message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</section></div>}
  </>;
}
