import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
if (!process.env.APP_URL) process.loadEnvFile(resolve(root, '.env'));
const base = process.env.APP_URL;
const password = randomBytes(24).toString('hex');
const username = 'smoke_' + randomBytes(8).toString('hex');
const headers = { 'Content-Type': 'application/json', Origin: new URL(base).origin };
const request = (path, init = {}) => fetch(new URL(path, base), { ...init, redirect: 'manual', signal: AbortSignal.timeout(15000) });
assert.equal((await request('/api/health/live')).status, 200);
assert.equal((await request('/api/health/ready')).status, 200);
assert.equal((await request('/')).status, 307);
assert.equal((await request('/api/auth/session')).status, 401);
assert.equal((await request('/api/auth/register', { method: 'POST', headers: { ...headers, Origin: 'https://invalid.example' }, body: JSON.stringify({ username, password }) })).status, 403);
const registered = await request('/api/auth/register', { method: 'POST', headers, body: JSON.stringify({ username, password, realName: '脚手架验证' }) });
assert.equal(registered.status, 201);
const cookie = registered.headers.get('set-cookie').split(';')[0];
const payload = await registered.json();
assert.equal(payload.user.role, 'member');
assert.equal(payload.user.displayName, '脚手架验证');
assert.ok(!JSON.stringify(payload).includes('passwordHash'));
assert.match(registered.headers.get('set-cookie'), /HttpOnly/i);
assert.equal((await request('/api/auth/session', { headers: { Cookie: cookie } })).status, 200);
assert.equal((await request('/api/auth/register', { method: 'POST', headers, body: JSON.stringify({ username, password }) })).status, 409);
assert.equal((await request('/api/auth/logout', { method: 'POST', headers: { ...headers, Cookie: cookie } })).status, 403);
assert.equal((await request('/api/auth/logout', { method: 'POST', headers: { ...headers, Cookie: cookie, 'X-CSRF-Token': payload.csrfToken } })).status, 200);
assert.equal((await request('/api/auth/session', { headers: { Cookie: cookie } })).status, 401);
assert.equal((await request('/api/auth/login', { method: 'POST', headers, body: JSON.stringify({ username, password: 'incorrect-password' }) })).status, 401);
assert.equal((await request('/api/auth/login', { method: 'POST', headers, body: JSON.stringify({ username, password }) })).status, 200);
const secretFile = process.env.ADMIN_BOOTSTRAP_PASSWORD_FILE;
const adminPassword = (await readFile(resolve(root, secretFile), 'utf8')).trim();
const admin = await request('/api/auth/login', { method: 'POST', headers, body: JSON.stringify({ username: process.env.ADMIN_BOOTSTRAP_USERNAME, password: adminPassword }) });
assert.equal(admin.status, 200);
assert.equal((await admin.json()).user.role, 'admin');
console.log('PASS: health, protected page, registration, login, admin bootstrap, Origin, CSRF, cookie and session revocation.');
console.log('Created disposable member ' + username + '; this script writes to the configured database.');
