import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { randomUUID } from 'node:crypto';
import net from 'node:net';
import { mkdir } from 'node:fs/promises';
import { closeDb, getPool, createBoss } from '@acm/db/server';
import { hashPassword } from '../packages/core/src/application/auth';
const { chromium } = createRequire(new URL('../packages/core/package.json', import.meta.url))('playwright-core');
const password = randomUUID() + randomUUID(), suffix = randomUUID().slice(0, 8), username = `ui_${suffix}`, memberName = `member_${suffix}`;
const pool = getPool(), servers: net.Server[] = [];
const ids: string[] = [];
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
const boss = createBoss();
async function forward(port: number, host: string) {
  const server = net.createServer(socket => {
    const upstream = net.connect({ port, host }); socket.pipe(upstream); upstream.pipe(socket);
    socket.on('error', () => upstream.destroy()); upstream.on('error', () => socket.destroy()); socket.on('close', () => upstream.destroy()); upstream.on('close', () => socket.destroy());
  });
  await new Promise<void>((resolve, reject) => { server.once('error', reject); server.listen(port, '127.0.0.1', resolve); }); servers.push(server);
}
try {
  assert.equal((await pool.query('SELECT enabled FROM collection_control WHERE id=1')).rows[0].enabled, false, 'Run UI validation while collection is paused');
  const hash = await hashPassword(password);
  const inserted = (await pool.query<{ id: string }>("INSERT INTO users(username,password_hash,role) VALUES ($1,$3,'admin'),($2,$3,'member') RETURNING id", [username, memberName, hash])).rows;
  ids.push(...inserted.map(r => r.id));
  await forward(3000, 'web'); await forward(6080, 'worker');
  browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1400, height: 1100 } });
  const page = await context.newPage();
  await page.goto('http://localhost:3000/admin/connections');
  await page.getByLabel('用户名').fill(username); await page.getByLabel('密码').fill(password);
  await page.getByRole('button', { name: '登录', exact: true }).click(); await page.waitForURL('http://localhost:3000/');
  await page.getByRole('link', { name: '管理平台登录' }).click();
  await page.getByRole('heading', { name: '平台采集连接', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '获取验证码', exact: true }).isDisabled(), true);
  const iframe = page.locator('iframe[title="QOJ 专用浏览器远程桌面"]');
  assert.ok((await iframe.getAttribute('src')).startsWith('http://localhost:6080/vnc.html'));
  const remoteDesktop = page.frameLocator('iframe[title="QOJ 专用浏览器远程桌面"]');
  await remoteDesktop.getByText('noVNC', { exact: true }).first().waitFor({ timeout: 15000 });
  await remoteDesktop.locator('#noVNC_password_input').waitFor({ state: 'visible', timeout: 30000 });
  await mkdir('/tmp/web-probe', { recursive: true }); await page.screenshot({ path: '/tmp/web-probe/connections.png', fullPage: true });
  if (process.env.WEB_PROBE_LUOGU_CAPTCHA === '1') {
    const section = page.locator('section').filter({ has: page.getByRole('heading', { name: '洛谷登录', exact: true }) });
    await section.getByLabel('登录账号').fill('Nick1024');
    const beginning = page.waitForResponse((response: { url(): string; request(): { method(): string } }) => response.url().endsWith('/luogu/login-attempts') && response.request().method() === 'POST', { timeout: 125000 });
    await section.getByRole('button', { name: '获取验证码', exact: true }).click();
    await section.getByRole('status').getByText('正在连接洛谷并获取图形验证码，请稍候…', { exact: true }).waitFor();
    const response = await beginning;
    const challenge = await response.json();
    assert.equal(response.status(), 201, challenge.message ?? 'Real Luogu captcha creation failed');
    await section.getByRole('status').getByText('验证码已获取，请填写密码和图形验证码。', { exact: true }).waitFor();
    const image = section.getByAltText('洛谷验证码'); await image.waitFor();
    await page.waitForFunction(`(() => { const img = document.querySelector('img[alt="洛谷验证码"]'); return img?.complete && img.naturalWidth > 0; })()`);
    const first = await page.request.get(`http://localhost:3000${challenge.captchaUrl}`);
    const repeated = await page.request.get(`http://localhost:3000${challenge.captchaUrl}`);
    assert.equal(first.status(), 200); assert.match(first.headers()['content-type'], /^image\//);
    assert.deepEqual(await first.body(), await repeated.body());
    await section.screenshot({ path: '/tmp/web-probe/luogu-captcha.png' });
    const refreshing = page.waitForResponse((response: { url(): string }) => response.url().endsWith('/refresh-captcha'), { timeout: 125000 });
    await section.getByRole('button', { name: '换一张', exact: true }).click();
    const refreshed = await refreshing; assert.equal(refreshed.status(), 200); assert.equal((await refreshed.json()).version, 2);
    await section.getByRole('status').getByText('验证码已刷新，请输入新图片中的字符。', { exact: true }).waitFor();
    assert.ok((await image.getAttribute('src')).endsWith('?v=2'));
    await section.getByRole('button', { name: '取消', exact: true }).click();
    await section.getByRole('status').getByText('本次洛谷登录已取消。', { exact: true }).waitFor();
    assert.equal((await page.request.get(`http://localhost:3000${challenge.captchaUrl}`)).status(), 409);
    console.log(JSON.stringify({ event: 'luogu_captcha_ui_probe_passed', checks: ['real captcha displayed', 'visible progress', 'stable repeat reads', 'refresh version', 'cancel invalidation'], credentialsSubmitted: false }));
  }
  const luoguSection = page.locator('section').filter({ has: page.getByRole('heading', { name: '洛谷登录', exact: true }) });
  await page.route('**/api/admin/connections/luogu/login-attempts', (route: { fulfill(input: { status: number; contentType: string; body: string }): Promise<void> }) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ code: 'NETWORK_ERROR', message: '服务器连接洛谷失败或请求超时，请稍后重试' }) }));
  await luoguSection.getByLabel('登录账号').fill('OfflineFixture');
  await luoguSection.getByRole('button', { name: '获取验证码', exact: true }).click();
  await luoguSection.getByRole('status').getByText('服务器连接洛谷失败或请求超时，请稍后重试', { exact: true }).waitFor();
  assert.equal(await luoguSection.getByRole('button', { name: '获取验证码', exact: true }).isEnabled(), true);
  await page.unroute('**/api/admin/connections/luogu/login-attempts');
  await luoguSection.getByLabel('登录账号').fill('');
  const sessionResponse = await page.request.get('http://localhost:3000/api/auth/session');
  const session = await sessionResponse.json();
  assert.equal((await page.request.get('http://localhost:3000/api/me')).status(), 200);
  assert.equal((await page.request.get('http://localhost:3000/api/leaderboard?limit=1')).status(), 200);
  assert.equal((await page.request.get('http://localhost:3000/api/leaderboard?from=2026-02-30&to=2026-03-01')).status(), 400);
  assert.equal((await page.request.get(`http://localhost:3000/api/members/${ids[1]}/solves`)).status(), 200);
  const headers = { origin: 'http://localhost:3000', 'x-csrf-token': session.csrfToken };
  assert.equal((await page.request.put('http://localhost:3000/api/me', { headers, data: { realName: 'UI fixture' } })).status(), 200);
  assert.equal((await page.request.put('http://localhost:3000/api/me', { headers: { ...headers, 'x-csrf-token': 'invalid' }, data: { realName: '' } })).status(), 403);
  assert.equal((await page.request.post('http://localhost:3000/api/admin/sync', { headers, data: {} })).status(), 409);
  assert.equal((await page.request.get('http://localhost:3000/api/members/not-a-uuid')).status(), 400);
  const memberContext = await browser.newContext(); const memberPage = await memberContext.newPage();
  const memberLogin = await memberPage.request.post('http://localhost:3000/api/auth/login', { headers: { origin: 'http://localhost:3000' }, data: { username: memberName, password } });
  assert.equal(memberLogin.status(), 200);
  assert.equal((await memberPage.request.get('http://localhost:3000/api/admin/platforms')).status(), 403);
  const memberSession = await memberLogin.json();
  const candidate = await memberPage.request.put('http://localhost:3000/api/me/platform-accounts/codeforces', { headers: { origin: 'http://localhost:3000', 'x-csrf-token': memberSession.csrfToken }, data: { target: 'HttpOfflineFixture' } });
  assert.equal(candidate.status(), 202);
  assert.equal((await pool.query('SELECT candidate_state FROM platform_bindings WHERE user_id=$1', [ids[1]])).rows[0].candidate_state, 'pending');
  const anonymous = await browser.newContext();
  assert.equal((await anonymous.request.get('http://localhost:3000/api/leaderboard')).status(), 401);
  assert.equal((await pool.query('SELECT enabled FROM collection_control WHERE id=1')).rows[0].enabled, false);
  console.log(JSON.stringify({ event: 'web_probe_passed', checks: ['administrator page', 'embedded noVNC', 'visible Luogu failure and retry', 'member API', 'Origin/CSRF/role', 'date and ID validation', 'paused sync', 'queued candidate without fetching'], screenshot: '/tmp/web-probe/connections.png' }));
} finally {
  await browser?.close(); for (const server of servers) await new Promise<void>(resolve => server.close(() => resolve()));
  await boss.start();
  const runs = (await pool.query<{ id: string; job_id: string; queue: string }>('SELECT r.id,r.job_id,r.queue FROM sync_runs r JOIN platform_bindings b ON b.id=r.binding_id WHERE b.user_id=ANY($1::uuid[])', [ids])).rows;
  for (const run of runs) if (run.job_id) await boss.cancel(run.queue, run.job_id);
  await pool.query('DELETE FROM sync_runs WHERE id=ANY($1::uuid[])', [runs.map(r => r.id)]);
  await pool.query('DELETE FROM users WHERE id=ANY($1::uuid[])', [ids]);
  await boss.stop(); await closeDb();
}
